before_install:
  - export PATH=$PATH:$(pwd)
  - export PERL5LIB=PERL5LIB:$HOME/lib/perl5
  - yes no | sudo apt-get install bioperl
  - cpanm -l ~ Math::Gauss
script: true
install:
  - bash tests/unittests/Kendall.pl.sh
  - bash tests/unittests/randTrees.pl.sh
  - bash tests/unittests/avgstdev.pl.sh
language: shell
addons:
  apt:
    packages:
      -realpath
